Feat add segment analytics
phakphum-dev/otog-frontend pull request #27
Opened 2022-08-04 09:52 UTC by karnjj

2022-08-04 10:05 UTC, Anon-136 requested changes

2022-08-04 10:05 UTC, Anon-136 commented on src/context/AnalyticsContext.tsx
> +}
เอาไว้ใช้ทำไรอะ

2022-08-04 10:05 UTC, Anon-136 commented on src/context/AnalyticsContext.tsx
> +  ])
analytics นี่ init แค่ครั้งเดียวปะ
ถ้า init ครั้งเดียวเอาออกไปข้างนอกได้ปะ

2022-08-04 10:05 UTC, Anon-136 commented on src/pages/_app.tsx
> +                <AnalyticsProvider apiKey={SEGMENT_API_KEY}>
นี่ด้วย ถ้า API_KEY เป็น const ก็ยกไปไว้อีกไฟล์เลย

2022-08-04 10:08 UTC, karnjj commented on src/context/AnalyticsContext.tsx
> +}
เอาไว้ไป track พวก onClick event ไรงี้

2022-08-04 10:12 UTC, karnjj commented on src/context/AnalyticsContext.tsx
> +  ])
Umm. Like firebase right ?

2022-08-04 10:23 UTC, Anon-136 commented on src/context/AnalyticsContext.tsx
> +  ])
ใช่ ๆ แล้วก็ทำให้เป็น Client Side only ด้วย

2022-08-05 14:10 UTC, karnjj commented on src/components/SegmentAnalytics.tsx
> +}
fixed

2022-08-05 14:11 UTC, Anon-136 approved these changes

2022-08-05 14:35 UTC, merged