Style copy button
phakphum-dev/otog-frontend pull request #73
Opened 2023-04-28 16:29 UTC by MasterIceZ

OK Anos merge me
https://github.com/phakphum-dev/otog-frontend/issues/71

2023-04-28 16:39 UTC, Anon-136 commented
doesn't help #71 :(

2023-05-04 16:22 UTC, Anon-136 requested changes

2023-05-04 16:22 UTC, Anon-136 commented on src/pages/problem/[id].tsx
> -          variant="ghost"
can you add padding so that it help #71

2023-05-04 16:22 UTC, MasterIceZ commented on src/pages/problem/[id].tsx
> -          variant="ghost"
No

2023-05-09 11:19 UTC, Anon-136 commented
fixed in 7c60727

2023-05-09 11:19 UTC, closed without merging